### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by vovabatsyk** [vovabatsyk/homepage-.net#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ghost** [comment]
<h3>SUMMARY</h3>
                                <ul class="timeline">
                                    <li>Result-oriented, highly motivated Software Developer. Proficient both in
                                        Front-end and Backend technologies.</li>
                                    <li>Key area of technical expertise covers JavaScript, React/Redux, ASP.Net Core
                                    </li>
                                    <li>Proven ability to keep the balance between experimenting with new frameworks and
                                        libraries,
                                        and importance of timely delivery of a visually appealing, fully functional
                                        product covering
                                        business needs.</li>
                                    <li>Proven record of success as a Full Stack web developer; strong adherence to the
                                        product
                                        quality (Clean code, TDD, and e2e testing); able to work independently and in
                                        team
                                        environment, comfortable with Agile (Scrum) methodologies.</li>
                                </ul>
