### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by vovabatsyk** [vovabatsyk/homepage-.net#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by ghost** [comment]
<h3>Education</h3>
                                <ul class="timeline">
                                    <li>
                                        <div><em>December 2005 &ndash; April 2010</em></div>
                                        <div><strong>Master in Law</strong> at
                                            <a href="https://www.lvduvs.edu.ua/" target="_blank"
                                                rel="external"><strong>Lviv State University of Internal
                                                    Affairs</strong></a>
                                        </div>
                                    </li>
                                    <li>
                                        <div><em> December 2019 &ndash; until now</em>
                                        </div>
                                        <div><strong>Software development</strong> at
                                            <a href="hhttps://lviv.itstep.org/" rel="external"><strong>Computer Academy
                                                    IT Step</strong></a>
                                        </div>
                                    </li>
                                </ul>
                                <h3>EXPERIENCE</h3>
                                <ul class="timeline">
                                    <li>
                                        <p><em>January 2012 – August 2017</em></p>
                                        <p><strong> Armed Forces of Ukraine</strong></p>
                                    </li>
                                    <li>
                                        <p><em>August 2018 – until now</em></p>
                                        <p><strong>Lviv City Council</strong></p>
                                    </li>
                                </ul>
