### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by vovabatsyk** [vovabatsyk/homepage-.net#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ghost** [comment]
<section>
                                <h3>Skills and Awards</h3>
                                <ul class="timeline">
                                    <ul>
                                        <li class="details">
                                            <input type="checkbox" id="frontend">
                                            <label for="frontend" class="summary">
                                                <strong>Front-End</strong>
                                            </label>
                                            <div class="labels">
                                                <a rel="external" class="label">Javascript</a>
                                                <a rel="external" class="label">Angular</a>
                                                <a rel="external" class="label">Vue.js</a>
                                                <a rel="external" class="label">React</a>
                                                <a rel="external" class="label">Redux</a>
                                                <a rel="external" class="label">TypeScript</a>
                                                <a rel="external" class="label">jQuery</a>
                                                <a rel="external" class="label">HTML5</a>
                                                <a rel="external" class="label">Bootstrap</a>
                                                <a rel="external" class="label">CSS3(LESS, SASS)</a>
                                            </div>
                                        </li>
                                        <li class="details">
                                            <input type="checkbox" id="backend">
                                            <label for="backend" class="summary">
                                                <strong>Back-End</strong>
                                            </label>
                                            <div class="labels">
                                                <a rel="external" class="label">C#</a>
                                                <a rel="external" class="label"> Asp.Net (.Net Framework & .Net
                                                    Core)</a>
                                                <a rel="external" class="label">SQL</a>
                                                <a rel="external" class="label">T-SQL</a>
                                                <a rel="external" class="label">MS SQL Server</a>
                                                <a rel="external" class="label">Entity Framework</a>
                                                <a rel="external" class="label">MVC</a>
                                            </div>
                                        </li>
                                        <li class="details">
                                            <input type="checkbox" id="desktop">
                                            <label for="desktop" class="summary">
                                                <strong>Desktop</strong>
                                            </label>
                                            <div class="labels">
                                                <a rel="external" class="label">Windows Forms</a>
                                                <a rel="external" class="label">WPF</a>
                                                <a rel="external" class="label">MVVM</a>
                                            </div>
                                        </li>
                                        <li class="details">
                                            <input type="checkbox" id="version-control">
                                            <label for="version-control" class="summary">
                                                <strong>Version Control</strong>
                                            </label>
                                            <div class="labels">
                                                <a rel="external" class="label">Git</a>
                                                <a rel="external" class="label" target="_blank"
                                                    href="https://github.com/vovabatsyk">GitHub</a>
                                                <a rel="external" class="label" target="_blank"
                                                    href="https://gitlab.com/webproger.ua">GitLab</a>
                                            </div>
                                        </li>
                                        <li class="details">
                                            <input type="checkbox" id="project-management">
                                            <label for="project-management" class="summary">
                                                <strong>Project Management</strong>
                                            </label>
                                            <div class="labels">
                                                <a rel="external" class="label">Scrum</a>
                                                <a rel="external" class="label">Kanban</a>
                                                <a rel="external" class="label">Trello</a>
                                            </div>
                                        </li>
                                        <li class="details">
                                            <input type="checkbox" id="testing">
                                            <label for="testing" class="summary">
                                                <strong>Testing</strong>
                                            </label>
                                            <div class="labels">
                                                <a rel="external" class="label">Unit testing</a>
                                                <a rel="external" class="label">e2e testing</a>
                                                <a rel="external" class="label">API Testing (Google Postman)</a>
                                            </div>
                                        </li>
                                        <li class="details">
                                            <input type="checkbox" id="tools">
                                            <label for="tools" class="summary">
                                                <strong>UX Development Tools </strong>
                                            </label>
                                            <div class="labels">
                                                <a rel="external" class="label">Webpack</a>
                                                <a rel="external" class="label">NPM - Node Package Manager</a>
                                                <a rel="external" class="label">Nuget Package Manager</a>
                                                <a rel="external" class="label">VS 2019</a>
                                                <a rel="external" class="label">VS Code</a>
                                                <a rel="external" class="label">Chrome dev tools</a>
                                            </div>
                                        </li>
                                    </ul>
                            </section>
